### ISSUE TITLE
Commits and other related issues are not displayed in Huboard cards

### ISSUE THREAD

**Issue by patdolem** [rauhryan/huboard#458]
Commits and other related issues are not displayed in Huboard cards while they are existing in GitHub.
The impact is that we miss very important information related to why an issue is closed, and we have to open it in Github to see the details and understand what is going on.

**Comment by droopy12** [comment]
:+1:

**Comment by rauhryan** [comment]
@patdolem @droopy12 

working on the UX for displaying referenced commits, due to an API constraint we have to make an additional call to get the commit message and commit url.

![commit ux](http://f.cl.ly/items/2R322r3j2O3W0M301g29/Screen%20Recording%202015-05-13%20at%2010.37%20AM.gif)

What  do you think of this UX, it's a bit unusual but we think it's "easily learned"

**Comment by patdolem** [comment]
@rauhryan this UX is a bit surprising. I would prefer to get the commit straight forward. Is this related to the GitHub API? Is this something GitHub would be willing to fix?

**Comment by rauhryan** [comment]
:boom: :tada:

**Comment by droopy12** [comment]
I usually want to see if and when something has changed so this blurry solution would be ok :+1: 
Funny solution though :ghost:
