### ISSUE TITLE
Rendering each card is slow

### ISSUE THREAD

**Issue by seanlinsley** [rauhryan/huboard#482]
Our backlog column has ~160 tickets in it. As you can see in the Ember Inspector screenshot below, rendering each card takes about 5 milliseconds, which adds up to 800 milliseconds.

![screen shot 2015-01-19 at 8 00 20 pm](https://cloud.githubusercontent.com/assets/688886/5811041/d37ad2a2-a015-11e4-8696-7c5941141cb6.png)

It seems like the fastest option would be to draw the whole `CollectionView` inside a temporary document, then insert the whole thing into the DOM. Unfortunately I haven't been able to find anyone doing that ¯\\_(ツ)_/¯

Another way to speed up render time would be to simply do less, by only rendering the cards within the viewport. Towards that end I found:
- [ember-cloaking](https://github.com/eviltrout/ember-cloaking) (+ [blog post](http://eviltrout.com/2014/01/04/hiding-offscreen-ember.html))
- [list-view](https://github.com/emberjs/list-view)

**Comment by rauhryan** [comment]
We have a long running branch to speed up the card rendering https://github.com/rauhryan/huboard/tree/rauhryan/perf-observe-array

It currently uses the cloaking view, the list-view turned our really awkward for drag and drop because everything this translated using css3 translate

While cloaking view does speed things up, the way array observing works in ember makes things behave very strangely with drag and drop

It's close tho, so hopefully we'll have it finished up soon

**Comment by discorick** [comment]
Card rendering speed has improved quite a bit post ember 1.13, closing
