### ISSUE TITLE
Constantly pinging Github, thousands of requests being made.

### ISSUE THREAD

**Issue by lopesc** [rauhryan/huboard#504]
Hi,

I am experiencing a major issue with the Enterprise version of Huboard.  It is constantly sending requests to Github at a rate of thousands per minute. Most of these requests stall, and Huboard  becomes slow and unusable, eventually crashing.

![huboard_requests](https://cloud.githubusercontent.com/assets/7646447/6158361/6fc6e898-b241-11e4-9508-3c9ad3c0ac5f.PNG)

**Comment by rauhryan** [comment]
The browser shouldn't be making requests directly to GitHub. 

Depending on which version of HuBoard Enterprise you are running it could be an issue that we have fixed regarding websockets failing and endlessly pinging the server making HuBoard very slow. 

In order to help you without discussing sensitive information, please open a support ticket by sending an email to support@huboard.com
