### ISSUE TITLE
Escape button horror 

### ISSUE THREAD

**Issue by codeyash** [rauhryan/huboard#511]
I opened a issue. Edited it for 5 mins. Accidentally pressed escape. BOOM.

Everything is lost. It should ask or atleast save that in session so that if I open that issue it shows same content to me.

Please fix it.

-Yash

**Comment by sfermigier** [comment]
Same for me. Also same if you click outside the issue area. This is specially annoying because when you open the "apply label" popup, you have to do something to close it, and it's easy to do it wrong.

A solution could be to have a "submit" and a "cancel" button instead of just "submit", and don't close the form of escape or outside click.
