### ISSUE TITLE
[FEATURE REQ] Add option to specify filters in URL

### ISSUE THREAD

**Issue by giacecco** [rauhryan/huboard#530]
E.g. ```https://huboard.com/theodi/shared#/``` is my dev team's planning Huboard. When I want to see only the issues labelled with "OA" I need every time to select that manually. It would be great if I could create a permanent link to something like ```https://huboard.com/theodi/shared#/?filter=OA``` instead. Moreover, when I create a new issue from that URL, the OA label should be already pre-selected. 

Of course the same would work specifying more filters, e.g. ```https://huboard.com/theodi/shared#/?filter=OA,1pt```.

This could be combined with other features requests about _excluding_ labels instead. For example something like ```https://huboard.com/theodi/shared#/?filter=+OA,-1pt``` could show all issues labelled with 'OA' that are not labelled with '1pt'.

Thanks!

**Comment by discorick** [comment]
Are you meaning saving a name permanent filter? Currently HuBoard does support sharing filters using the generated query string of the current filter.

**Comment by patcon** [comment]
Thanks! @discorick care to link to those docs for the next person who finds this from the googles?

**Comment by discorick** [comment]
@patcon You bet... awkwardly enough we have no docs for filters at the moment, we will get right on that and I will make sure to follow up and post them on this thread. Thanks!

**Comment by patcon** [comment]
Thanks @discorick! Any chance you can also explain it here for me so that I can make my link? ;)

**Comment by discorick** [comment]
@patcon Of course! As you select filters in HuBoard you will notice the url bar change like so:

![image](https://cloud.githubusercontent.com/assets/1130665/15764146/ee63d672-28e5-11e6-8ab3-0322ecd4c254.png)

Simply copy that url and share, the board should load with the selected filter options automatically enabled!

Note: There is a regression I will be working on tomorrow that can make this feature do strange things occasionally, more info here: https://github.com/huboard/huboard-web/issues/310

**Comment by patcon** [comment]
Ah, I may have hit another bug. Explained it in an email, but to quickly recap -- Milestones seem to need to be clicked twice before they're filtered completely (rather than visually muted after the first click). The url doesn't change until the second click. This wasn't obvious to me for the past few months that I've been using HuBoard :)

**Comment by discorick** [comment]
> The url doesn't change until the second click

This is actually intentional behavior. Since HuBoard has two state filters (first click is dim, second is completely hidden) we decided against filtering on Dims. I suppose it can be a little bit unexpected, especially given the lack of prior docs. 

An elaboration on this is any filters within the same group, lets say milestones, cannot mix and match the dim feature. So if a milestone is fully (two click) filtered then any other milestones you select will also "jump" to also completely hidden.

**Comment by patcon** [comment]
Thanks figured as much. If you're open to suggestions, I would suggest hiding first, then dim on second (removing filter if you feel that's correct), since that first click should get the filter imho (for max discoverability without consulting docs and pestering you guys). I can't be the only person who simply never discovered that due to it not being the first click :)
