### ISSUE TITLE
Boolean filtering is required

### ISSUE THREAD

**Issue by patdolem** [rauhryan/huboard#544]
Filters can’t be added together, e.g. issues assigned to userA and userB and unassigned, or issues in milestoneX and milestoneY.

**Comment by rauhryan** [comment]
@patdolem we just pushed this live to huboard.com

this turned out to be quite the effort to get the way we think you want it. 

@discorick did a complete overhaul of our filtering system and has set some ground work to allow for swappable filtering strategies in the future. 

I've been wrapping up the next enterprise release which includes a TON of changes. We have a release that's ready to go that DOESN'T have the boolean filters included. 

We can delay sneak it in but we'd feel a lot better about it if we could get some feedback from you and your team before we merge this into enterprise. 

Thanks!

**Comment by patdolem** [comment]
@rauhryan I tested it and it looks good. I noticed the operator used for team members, milestones is OR while it's AND for labels. This is OK but we would like to be able to have the choice between AND and OR for labels.
OR is good for team members, repos and milestones.
I wasn't able to test for the repos as there was no possibility to link repos. Please confirm it if it also OR for repos.

**Comment by rauhryan** [comment]
Yes repos are OR'd
