### ISSUE TITLE
referenced commits text is blurred then lorem ipsumed

### ISSUE THREAD

**Issue by mderazon** [rauhryan/huboard#553]
Not my lorem ipsum there

![screen shot 2015-05-17 at 11 56 09 am](https://cloud.githubusercontent.com/assets/717076/7669742/f0ac9ffe-fc8b-11e4-97c7-6b3677d27ff5.png)

**Comment by mderazon** [comment]
related to #458 ?

**Comment by rauhryan** [comment]
The lorem is a placeholder that we use until we make a round trip to the API to get the commit message. 

Rather than making an N+1 API call when you load the issue, we blur the placeholder out and fetch the new info on hover. 

I tried to explain it in #458, it's not the most ideal UX but we throw it out there to see what users thought. 

Are you not seeing the right commit message side load when you hover the event?

**Comment by discorick** [comment]
@mderazon I tracked down why this is happening, there are empty reference payloads that github sends for issue references along with the commit references, we should have a fix pushed up in the next day or so :)

**Comment by mderazon** [comment]
cool, thanks :+1:
